name: Build and Publish

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows x64 platform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release Directory
      run: mkdir bin\Release\net8.0-win-x64

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Replace with the exact version of .NET 8.0 you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release -p:OutputPath=bin\Release\net8.0-win-x64\

    - name: Upload Executables and Additional Files
      id: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Executables and Additional Files
        path: ./bin/Release/net8.0-win-x64

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Replace with your desired release tag/version
        files: |
          ./bin/Release/net8.0-win-x64/YimMenu Updater.exe
          ./bin/Release/net8.0-win-x64/dllinject.exe

    - name: Release URL
      run: echo "The release URL is ${{ steps.create_release.outputs.upload_url }}"
